# Generated by Django 5.2.8 on 2025-11-16 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('filters', models.JSONField(blank=True, null=True)),
                ('data_snapshot', models.JSONField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_created', to='users.user')),
            ],
            options={
                'db_table': 'reports',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['name'], name='reports_name_24ae72_idx'), models.Index(fields=['created_at'], name='reports_created_c5f642_idx')],
            },
        ),
    ]
