# Generated by Django 5.2.8 on 2025-11-13 22:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dossiers', '0001_initial'),
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('service_type', models.CharField(choices=[('flight', 'Flight'), ('hotel', 'Hotel'), ('cruise', 'Cruise'), ('bus', 'Bus')], max_length=20)),
                ('booking_date', models.DateField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('departure_date', models.DateField(blank=True, null=True)),
                ('origin', models.CharField(blank=True, max_length=100, null=True)),
                ('destination', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('ticket_number', models.CharField(blank=True, max_length=100, null=True)),
                ('locator', models.CharField(blank=True, max_length=100, null=True)),
                ('total_client', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_supplier', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('dossier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='dossiers.dossier')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='suppliers.supplier')),
            ],
            options={
                'db_table': 'services',
                'ordering': ['start_date'],
                'indexes': [models.Index(fields=['service_type'], name='services_service_df1ac4_idx'), models.Index(fields=['dossier'], name='services_dossier_183ef0_idx')],
            },
        ),
    ]
