# Generated by Django 5.2.8 on 2025-11-09 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('client_type', models.CharField(choices=[('person', 'Person'), ('company', 'Company')], max_length=20)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('document_type', models.CharField(choices=[('dni', 'DNI'), ('nie', 'NIE'), ('passport', 'Passport')], max_length=20)),
                ('document_number', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=120, unique=True)),
                ('phone_mobile', models.CharField(blank=True, max_length=20, null=True)),
                ('phone_landline', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True)),
                ('province', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'clients',
                'indexes': [models.Index(fields=['last_name', 'first_name'], name='clients_last_na_7dc725_idx'), models.Index(fields=['email'], name='clients_email_4c8bec_idx')],
                'constraints': [models.UniqueConstraint(fields=('document_type', 'document_number'), name='uniq_document')],
            },
        ),
    ]
