# Generated by Django 5.2.8 on 2025-11-16 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dossiers', '0001_initial'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('issue_date', models.DateField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_settled', models.BooleanField(default=False)),
                ('dossier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='dossiers.dossier')),
            ],
            options={
                'db_table': 'invoices',
                'ordering': ['-issue_date'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_services', to='invoices.invoice')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoiced_in', to='services.service')),
            ],
            options={
                'db_table': 'invoice_services',
            },
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['dossier'], name='invoices_dossier_4531da_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['code'], name='invoices_code_3167a5_idx'),
        ),
        migrations.AddIndex(
            model_name='invoiceservice',
            index=models.Index(fields=['invoice'], name='invoice_ser_invoice_8a3955_idx'),
        ),
        migrations.AddIndex(
            model_name='invoiceservice',
            index=models.Index(fields=['service'], name='invoice_ser_service_2452ae_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='invoiceservice',
            unique_together={('invoice', 'service')},
        ),
    ]
