# Generated by Django 5.2.8 on 2025-11-14 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('base_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('management_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_client', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_supplier', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='services.service')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='suppliers.supplier')),
            ],
            options={
                'db_table': 'products',
                'ordering': ['id'],
                'indexes': [models.Index(fields=['service'], name='products_service_911629_idx'), models.Index(fields=['supplier'], name='products_supplie_1396c7_idx')],
            },
        ),
    ]
