# Generated by Django 5.2.8 on 2025-11-15 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('file_name', models.CharField(max_length=200)),
                ('file_type', models.CharField(blank=True, max_length=50, null=True)),
                ('file_url', models.TextField(blank=True, null=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='services.service')),
            ],
            options={
                'db_table': 'documents',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['service'], name='documents_service_a1fc3a_idx'), models.Index(fields=['file_name'], name='documents_file_na_a53640_idx')],
            },
        ),
    ]
