# Generated by Django 5.2.8 on 2025-11-13 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dossier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=20)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('total_pvp', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_pending', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_invoiced', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dossiers', to='clients.client')),
            ],
            options={
                'db_table': 'dossiers',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['code'], name='dossiers_code_3dbea0_idx'), models.Index(fields=['status'], name='dossiers_status_c59538_idx'), models.Index(fields=['client'], name='dossiers_client__495fc7_idx')],
            },
        ),
    ]
